export const userTypes = {
  REGISTER_USER: 'REGISTER_USER',
  REGISTERING_USER: 'REGISTERING_USER',

  LOGIN_USER: 'LOGIN_USER',
  LOGINING_USER: 'LOGINING_USER',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGINGOUT_USER: 'LOGINGOUT_USER',

  GET_COMMENTS: 'GET_COMMENTS',
  GETING_COMMENTS: 'GETING_COMMENTS',

  ADD_COMMENT: 'ADD_COMMENT',
  ADDING_COMMENT: 'ADDING_COMMENT',

  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETING_COMMENT: 'DELETING_COMMENT',

  UPDATE_LIKE: 'UPDATE_LIKE',
  UPDATING_LIKE: 'UPDATING_LIKE',

  ADD_LIKE: 'ADD_LIKE',
};
