export const authActionType = {
  LOGIN_USER: 'LOGIN_USER',
  LOGING_USER: 'LOGING_USER',

  SET_AUTH_LOADING: 'SET_AUTH_LOADING',

  LOGOUT_USER: 'LOGOUT_USER',
  LOGING_OUT_USER: 'LOGING_OUT_USER',
};
