export const userActionTypes = {
  REMOVE_ADMINS: 'REMOVE_ADMINS',
  REMOVE_ADMIN: 'REMOVE_ADMIN',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',

  SET_SUPER_ADMIN_LOADING: 'SET_SUPER_ADMIN_LOADING',
  REMOVE_SUPER_ADMIN_LOADING: 'REMOVE_SUPER_ADMIN_LOADING',

  ADD_ADMIN: 'ADD_ADMIN',
  ADDING_ADMIN: 'ADDING_ADMIN',

  GET_ADMIN: 'GET_ADMIN',
  GETING_ADMIN: 'GETING_ADMIN',

  DELETE_ADMIN: 'DELETE_ADMIN',
  DELETING_ADMIN: 'DELETING_ADMIN',

  SEARCH_BY_EMAIL: 'SEARCH_BY_EMAIL',
  SEARCHING_BY_EMAIL: 'SEARCHING_BY_EMAIL',

  SEARCH_BY_NAME: 'SEARCH_BY_NAME',
  SEARCHING_BY_NAME: 'SEARCHING_BY_NAME',
};
