export const quizzesActionTypes = {
  GET_QUIZ: 'GET_QUIZ',
  GETING_QUIZ: 'GETING_QUIZ',

  SET_QUIZ_LOADING: 'SET_QUIZ_LOADING',

  REMOVE_QUIZ_LOADING: 'REMOVE_QUIZ_LOADING',

  REMOVE_QUIZ: 'REMOVE_QUIZ',

  ADD_QUIZ: 'ADD_QUIZ',
  ADDING_QUIZ: 'ADDING_QUIZ',

  DELETE_QUIZ: 'DELETE_QUIZ',
  DELETING_QUIZ: 'DELETING_QUIZ',

  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
};
