export const adminCourseTypes = {
  SET_LOADING: 'SET_LOADING',

  REMOVE_MESSAGE: 'REMOVE_MESSAGE',

  CREATE_COURSE: 'CREATE_COURSE',
  CREATING_COURSE: 'CREATING_COURSE',

  UPDATE_COURSE: 'UPDATE_COURSE',
  UPDATING_COURSE: 'UPDATING_COURSE',

  DELETE_COURSE: 'DELETE_COURSE',
  DELETING_COURSE: 'DELETING_COURSE',

  LIST_COURSE: 'LIST_COURSE',
  LISTING_COURSE: 'LISTING_COURSE',
};
