export const chapterTypes = {
  CREATE_CHAPTER: 'CREATE_CHAPTER',
  CREATING_CHAPTER: 'CREATING_CHAPTER',

  LIST_CHAPTER: 'LIST_CHAPTER',
  LISTING_CHAPTER: 'LISTING_CHAPTER',

  DELETE_CHAPTER: 'DELETE_CHAPTER',
  DELETING_CHAPTER: 'DELETING_CHAPTER',

  REMOVE_CHAPTER: 'REMOVE_CHAPTER',

  SET_LOADING: 'SET_LOADING',
  REMOVE_MESSAGE: 'REMOVE_MESSAGE',
};
