export const userActionTypes = {
  SET_USER_LOADING: 'SET_USER_LOADING',

  GET_USERS: 'GET_USERS',
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',

  REMOVE_USER: 'REMOVE_USER',
  REMOVE_USER_REQUEST: 'REMOVE_USER_REQUEST',

  SEARCH_BY_EMAIL: 'SEARCH_BY_EMAIL',
  SEARCHING_BY_EMAIL: 'SEARCHING_BY_EMAIL',

  SEARCH_BY_ID: 'SEARCH_BY_ID',
  SEARCHING_BY_ID: 'SEARCHING_BY_ID',

  DELETE_USERS: 'DELETE_USERS',
};
