export const commentActionType = {
  GET_COMMENT: 'GET_COMMENT',
  GETING_COMMENT: 'GETING_COMMENT',
  SET_COMMENT_LOADING: 'SET_COMMENT_LOADING',
  REMOVE_COMMENT_LOADING: 'REMOVE_COMMENT_LOADING',

  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETING_COMMENT: 'DELETING_COMMENT',

  REMOVE_COMMENT: 'REMOVE_COMMENT',
};
